server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  datasource:
    url: jdbc:h2:file:./data/nightvision
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true   # http://localhost:8080/h2-console 로 DB 조회 가능
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  inference-base-url: ${INFERENCE_BASE_URL:http://70.30.158.46:57243}
  inference-api-key: ${INFERENCE_API_KEY}
  upload-dir: ./uploads
  result-dir: ./results
  inference:
    timeout-minutes: 20
    max-retries: 2
